Repository K2InformaticsGmbH/imem, pull requests merged in 2019-08, with the labels that each got.

#265 win32 perf APIs and tracer fixes
  c_src/imem_win32.cpp
  c_src/win32_tests.cpp
  include/imem_tracer.hrl
  src/imem_merge.erl
  src/imem_tracer.erl
  src/imem_win32.erl
Labels: enhancement

#281 Disable win32 tests on non-win32 platforms
  rebar.config
  src/imem_win32.erl
Labels: enhancement

#284 send/receive support for ddTracer
  include/imem_tracer.hrl
  src/imem_tracer.erl
Labels: enhancement

#286 support windows (back) slashes for CIFS
  src/imem_file.erl
Labels: Size: 1, enhancement

#285 on demand cluster snapshotting API
  src/imem_snap.erl
Labels: enhancement

#287 lager_backend not replacing [*] in message
  src/imem_lager_backend.erl
Labels: bug
